language: objective-c
osx_image: xcode10.2
sudo: false

env:
  - iOS= DST='platform=iOS Simulator,name=iPhone Xs' ACTION=test DEVICE='iPhone Xs (12.2)' XC_SCHEME=Tests-iOS XC_PROJECT=Tests-iOS/Tests-iOS.xcodeproj BUILD_DEPENDENT_LIBRARIES=true
  - iOS= DST='platform=iOS Simulator,name=iPhone Xs' ACTION=test DEVICE='iPhone Xs (11.2)' XC_SCHEME=Tests-iOS XC_PROJECT=Tests-iOS/Tests-iOS.xcodeproj BUILD_DEPENDENT_LIBRARIES=false
  - macOS= DST='platform=OS X' ACTION=test XC_SCHEME=Tests-macOS XC_PROJECT=Tests-macOS/Tests-macOS.xcodeproj BUILD_DEPENDENT_LIBRARIES=true
  - macOS= DST='platform=OS X' ACTION=test XC_SCHEME=Tests-macOS XC_PROJECT=Tests-macOS/Tests-macOS.xcodeproj BUILD_DEPENDENT_LIBRARIES=false

before_install:
  - gem install cocoapods
  - gem install xcpretty --no-document
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "$DEVICE \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
  - echo "$SIMULATOR_ID"
  - ./scripts/before_install.sh

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace Tesseract-OCR-iOS.xcworkspace -list
  - if [ "$DST" != "platform=OS X" ]; then
      echo "$SIMULARTOR_ID";
      open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID || true; sleep 20;
    fi
  - xcodebuild -scheme "$XC_SCHEME" -destination "$DST" -project "$XC_PROJECT" clean build | xcpretty -tc;
  - xcodebuild -scheme "$XC_SCHEME" -destination "$DST" -project "$XC_PROJECT" -enableCodeCoverage YES $ACTION | xcpretty -tc;

after_success:
  ./scripts/coveralls.rb --extension m --extension mm --exclude-folder include --exclude-folder Tests --exclude-folder Tests-iOS --exclude-folder Tests-macOS
